# Form implementation generated from reading ui file 'c:\Users\amnah\OneDrive\Documents\Database\Project\gate.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Gate(object):
    def setupUi(self, Gate):
        Gate.setObjectName("Gate")
        Gate.resize(586, 579)
        self.centralwidget = QtWidgets.QWidget(parent=Gate)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(35, 100, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.GateNum = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.GateNum.setGeometry(QtCore.QRect(105, 110, 431, 22))
        self.GateNum.setObjectName("GateNum")
        self.GAddBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.GAddBtn.setGeometry(QtCore.QRect(325, 230, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.GAddBtn.setFont(font)
        self.GAddBtn.setObjectName("GAddBtn")
        self.GDeleteBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.GDeleteBtn.setGeometry(QtCore.QRect(445, 230, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.GDeleteBtn.setFont(font)
        self.GDeleteBtn.setObjectName("GDeleteBtn")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(270, 300, 281, 201))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        Gate.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Gate)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 586, 26))
        self.menubar.setObjectName("menubar")
        Gate.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Gate)
        self.statusbar.setObjectName("statusbar")
        Gate.setStatusBar(self.statusbar)

        self.retranslateUi(Gate)
        QtCore.QMetaObject.connectSlotsByName(Gate)

    def retranslateUi(self, Gate):
        _translate = QtCore.QCoreApplication.translate
        Gate.setWindowTitle(_translate("Gate", "MainWindow"))
        self.label.setText(_translate("Gate", "Gate Details"))
        self.label_3.setText(_translate("Gate", "Number"))
        self.GAddBtn.setText(_translate("Gate", "Add"))
        self.GDeleteBtn.setText(_translate("Gate", "Delete"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Gate", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Gate", "Gate Number"))
