# Form implementation generated from reading ui file 'c:\Users\amnah\OneDrive\Documents\Database\Project\login.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(657, 518)
        self.centralwidget = QtWidgets.QWidget(parent=login)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(120, 90, 451, 121))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.LoginBox = QtWidgets.QComboBox(parent=self.groupBox)
        self.LoginBox.setGeometry(QtCore.QRect(160, 60, 231, 22))
        self.LoginBox.setObjectName("LoginBox")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(60, 60, 81, 21))
        self.label_3.setObjectName("label_3")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(120, 230, 451, 161))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(50, 50, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(50, 100, 81, 16))
        self.label_2.setObjectName("label_2")
        self.Username = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.Username.setGeometry(QtCore.QRect(150, 50, 251, 22))
        self.Username.setObjectName("Username")
        self.Password = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.Password.setGeometry(QtCore.QRect(150, 100, 251, 22))
        self.Password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.Password.setObjectName("Password")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(180, 20, 361, 51))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.NextBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.NextBtn.setGeometry(QtCore.QRect(480, 420, 93, 28))
        self.NextBtn.setObjectName("NextBtn")
        login.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=login)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 657, 26))
        self.menubar.setObjectName("menubar")
        login.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=login)
        self.statusbar.setObjectName("statusbar")
        login.setStatusBar(self.statusbar)

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "MainWindow"))
        self.groupBox.setTitle(_translate("login", "User Type"))
        self.label_3.setText(_translate("login", "Login As:"))
        self.groupBox_2.setTitle(_translate("login", "Credentials"))
        self.label.setText(_translate("login", "Username: "))
        self.label_2.setText(_translate("login", "Password:"))
        self.label_4.setText(_translate("login", "Airport Management System"))
        self.NextBtn.setText(_translate("login", "Next"))
